### ISSUE TITLE
Contribution proposal

### ISSUE THREAD

**Issue by ark-tik** [rtarun9/Helios#4]
Hi, I recently got to know about this DirectX based graphic engine, and I'm a bit curious about learning and playing with DirectX for a while now, let me know if you need a contributor for this project. I'd love to contribute.

**Comment by rtarun9** [comment]
Hey @KartikShrivastava!
Thank you for showing your interest towards this project. As you can see by the last commit, this project has ended (for now at least).
If you are interested about learning about DirectX, I would recommend you check out https://github.com/GraphicsProgramming/learnd3d11, which is a current work in progress D3D11 community-based tutorial (D3D11 is a lot easier to learn and mess around with than D3D12). I'm not aware of any other open source D3D11 renderers but starting your own renderer by following the many tutorials can be really useful, which would also make contributing towards other open-source engines / renderers easier.

**Comment by ark-tik** [comment]
For sure, thanks a lot for the info.
